language: R
cache: packages
latex: false
sudo: false

r:
  - release
  - oldrel
  - devel

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - vegan
  - stats
  - sampling

before_install:
  - tlmgr install index
