language: r
cache: packages

r:
  - release
  - oldrel
  - devel

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - vegan
  - stats
  - sampling

before_install:
  - tlmgr install index
