language: R
cache: packages
sudo: false

r:
  - release
  - oldrel
  - devel

r_packages:
  - vegan
  - stats
  - sampling
  - roxygen2
  - knitr
  - rmarkdown
  - ggplot2
  - testthat

os:
  - linux
  - osx


