## datquality: Script to compare the ecological parameters of simulated and original data

datquality<-function(pilotdata, simdata, parameters, transformation, method){
        Par<-parameters
        MVD = function (Y, transformation, method) {
                if (transformation=="square root"){
                        Y.t<-Y^0.5
                        D<-vegdist(Y.t, method = method)
                }
                if (transformation=="fourth root"){
                        Y.t<-Y^0.25
                        D<-vegdist(Y.t, method = method)
                }
                if (transformation=="Log (X+1)"){
                        Y.t<-log(Y+1)
                        D<-vegdist(Y.t, method = method)
                }
                if (transformation=="P/A"){
                        Y.t<- 1 * (Y>0)
                        D<-vegdist(Y.t, method = method)
                }
                if (transformation=="none"){
                        Y.t<- Y
                        D<-vegdist(Y.t, method = method)
                }

                n = dim(as.matrix(D))
                ss = sum(D^2)/n
                v = ss/(n-1)
                return(v[1])
        }

        alfa = function (Y) {
                mean = mean(specnumber(Y))
                sd = sd(specnumber(Y))
                x<-c(mean, sd)
                return (x)
        }

        simpson = function (Y) {
                mean = mean(diversity(Y, index = "simpson"))
                sd = sd(diversity(Y, index = "simpson"))
                x<-c(mean, sd)
                return (x)
        }

        parameters<-as.data.frame(matrix(nrow= 2, ncol=8))
        rownames(parameters)<-c("Pilot data", "Simulated data")
        colnames(parameters)<-c("Samples", "Sites", "S.mean", "S.sd", "1-D.mean", "1-D.sd", "MVDmin", "MVDmax")
        parameters[1,1]<-nrow(pilotdata)
        parameters[2,1]<-nrow(simdata[[1]])
        parameters[1,2]<-try(length(levels(pilotdata$sites)), silent = T)
        if (parameters[1,2]==0){
                parameters[1,2]<-1
        }
        parameters[2,2]<-try(length(levels(simdata[[1]]$sites)), silent = T)
        if (parameters[2,2]==0){
                parameters[2,2]<-1
        }

        parameters[1,3:4]<-alfa(pilotdata)
        parameters[1,5:6]<-simpson(pilotdata)
        parameters[1,7]<-MVD(pilotdata, transformation=transformation, method=method)


        x<-matrix(nrow = length(simdata), ncol = 5)
        for (i in 1:length(simdata)){
                x[i,1:2]<-alfa(simdata[[i]][,1:Par$Sest])
                x[i,3:4]<-simpson(simdata[[i]][,1:Par$Sest])
                x[i,5]<-MVD(simdata[[i]][,1:Par$Sest], transformation=transformation, method=method)
                }
                parameters[2,3:6]<-apply(x[,1:4], 2, mean)
                parameters[2,7:8]<-range(x[,5])
        return(parameters)
}

##Description
#Function that estimates the average number of species and evenness per sampling unit; and the total multivariate dispersion of pilot data and simulated data.

##Usage

#datquality(pilotdata, simdata, parameters, transformation, method)

## Arguments

#pilotdata          Dataframe giving P/A or abundance (counts or coverage) of species.

#simdata            List of simulated data generated by SimDat.

#parameters           List of parameters generated by assempar.

#transformation     Mathematical function to reduce the weight of dominant species: "square root", "fourth root", "Log (X+1)", "P/A", "none".

#method             The name of any method used in vegdist{vegan} to calculate pairwise distances.
