##mseplot: Script to plot the MultSE and sampling effort

mseplot<-function(results, multi.site = TRUE){
        lower<-function(x){quantile(x,0.025)}
        upper<-function(x){quantile(x,0.975)}
        if (multi.site == TRUE){
                results$p.s<-factor(results$p.s)
                results$p.n<-factor(results$p.n)

                 #Sites
                sites.mse<-aggregate(MSE.sites~ simdata*p.s, data = results, mean)
                sites.mean<-aggregate(MSE.sites ~ p.s, data = sites.mse, mean)
                colnames(sites.mean)<-c("p.s", "mean")
                sites.lower<-aggregate(MSE.sites~ p.s, data = sites.mse, lower)
                colnames(sites.lower)<-c("p.s", "lower")
                sites.upper<-aggregate(MSE.sites~ p.s, data = sites.mse, upper)
                colnames(sites.upper)<-c("p.s", "upper")
                sites.results<-cbind(sites.mean, sites.upper[,2], sites.lower[,2])
                sites.results$p.s<-factor(sites.results$p.s)
                colnames(sites.results)<-c("levels", "mean", "upper", "lower")
                sites.results$sv<-c(rep("sites", nrow(sites.results)))

                #Samples
                n.mse<-aggregate(MSE.n~ simdata*p.n, data = results, mean)
                n.mean<-aggregate(MSE.n ~ p.n, data = n.mse, mean)
                colnames(n.mean)<-c("p.n", "mean")
                n.lower<-aggregate(MSE.n~ p.n, data = n.mse, lower)
                colnames(n.lower)<-c("p.n", "lower")
                n.upper<-aggregate(MSE.n~ p.n, data = n.mse, upper)
                colnames(n.upper)<-c("p.n", "upper")
                n.results<-cbind(n.mean, n.upper[,2], n.lower[,2])
                n.results$p.n<-factor(n.results$p.n)
                colnames(n.results)<-c("levels", "mean", "upper", "lower")
                n.results$sv<-c(rep("samples", nrow(n.results)))
                x<-rbind(sites.results, n.results)
                return(x)
        }
        if (multi.site == FALSE){
                results$p.n<-factor(results$p.n)
                n.mse<-aggregate(mSE~ simdata*p.n, data = results, mean)
                n.mean<-aggregate(mSE ~ p.n, data = n.mse, mean)
                colnames(n.mean)<-c("p.n", "mean")
                n.lower<-aggregate(mSE~ p.n, data = n.mse, lower)
                colnames(n.lower)<-c("p.n", "lower")
                n.upper<-aggregate(mSE~ p.n, data = n.mse, upper)
                colnames(n.upper)<-c("p.n", "upper")
                n.results<-cbind(n.mean, n.upper[,2], n.lower[,2])
                n.results$p.n<-factor(n.results$p.n)
                colnames(n.results)<-c("levels", "mean", "upper", "lower")
                return(n.results)
                }
}

##Description
#mseplots estimates the average of the MultSE generated for each source of variation according to
#the repetitions of each sampling design. Values of the mean, lower and upper quantiles are tabulated for
#each sampling effort. The values are summarized in a dataframe.

##Usage
#Plot MSE for sites and samples
#to.plot<- datplot(results, multi.site = TRUE)

#plot1<-ggplot(to.plot, aes(x=factor(levels), y=mean))+
#        geom_point()+
#        geom_errorbar(aes(ymin=lower, ymax=upper), width=.1)+
#        facet_grid(.~sv)+
#        theme_bw(base_size=16) +
#        ylab ("Multivariate pseudo SE")+
#        xlab("Sampling effort")

#Plot MSE for samples
#to.plot<- datplot(results, multi.site = FALSE)
#plot2<-ggplot(to.plot, aes(x=factor(levels), y=mean))+
#       geom_point()+
#        geom_errorbar(aes(ymin=lower, ymax=upper), width=.1)+
#        theme_bw(base_size=16) +
#        ylab ("Multivariate pseudo SE")+
#        xlab("Sampling effort")


## Arguments
#to.plot        dataframe generated by plot.MSE
#multi.site     Logical argument indicating whether several sites were simulated
